# Generated by Django 5.1.4 on 2026-07-03 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('motocicletas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(db_index=True, max_length=10)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono_cliente', models.CharField(blank=True, default='', max_length=20)),
                ('marca_moto', models.CharField(max_length=50)),
                ('modelo_moto', models.CharField(blank=True, default='', max_length=50)),
                ('descripcion_problema', models.TextField()),
                ('diagnostico', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('Recibida', 'Recibida'), ('En diagnóstico', 'En diagnóstico'), ('En reparación', 'En reparación'), ('Esperando repuesto', 'Esperando repuesto'), ('Lista para entregar', 'Lista para entregar'), ('Entregada', 'Entregada')], default='Recibida', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('monto_mano_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margen_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='clientes.cliente')),
                ('motocicleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='motocicletas.motocicleta')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotaOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='ordenes.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Nota de OT',
                'verbose_name_plural': 'Notas de OT',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='ordenes.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
